USE [Anvil.Test]
GO
INSERT INTO [dbo].[Mods]([Id],[Name],[Description],[Author],[UpdateUrl]) VALUES
('forge', 'Minecraft Forge', '', '', 'https://addons-ecs.forgesvc.net/api/v2/minecraft/modloader'),
('abnormals_core', 'Abnormals Core', 'The library mod used by all Abnormals mods. Adds support for various types of blocks, helps with registering, and adds tons of misc. utils.\n    Also comes with Endimator, an animation library that supports data-driven and coded animations.\n', 'Team Abnormals', ''),
('aquaculture', 'Aquaculture 2', 'Welcome to Aquaculture! An expansion of Minecraft''s fishing system.\n', 'Shadowclaimer, Girafi', ''),
('architectury', 'Architectury', 'A intermediary api aimed to ease developing multiplatform mods.\n', 'shedaniel', ''),
('backpacked', 'Backpacked', 'Adds a simple backpack to store more items', 'MrCrayfish', ''),
('backpacker', 'Backpacker', 'An addon for Backpacked that adds more variants of backpacks', 'MrCrayfish', ''),
('bambooeverything', 'Bamboo Everything', 'All things bamboo\n', 'Gaz(Gaz492)', ''),
('betteranimalsplus', 'Better Animals Plus', 'Companion mod to Better Animals adding new creatures with the Better Animals art style.', '', ''),
('botania', 'Botania', 'Botania is a mod that adds nature magic to Minecraft.', 'Vazkii, wiiv, williewillus, dylan4ever, Hubry', ''),
('buzzier_bees', 'Buzzier Bees', 'Buzzier Bees expands on the content introduced in 1.15, introducing candles, new building blocks, and more!\n', 'Team Abnormals', ''),
('catalogue', 'Catalogue', 'Updates Forge''s mod list with a new and improved design', 'MrCrayfish', ''),
('caves_and_cliffs', 'Caves And Cliffs', 'Minecraft Caves and Cliffs update!\r\n', 'supermj767', ''),
('cb_multipart', 'CBMultipart', 'Open source library for facilitation of multiple functional parts in the one block space.', 'ChickenBones, covers1624', ''),
('computercraft', 'CC: Tweaked', 'CC: Tweaked is a fork of ComputerCraft, adding programmable computers, turtles and more to Minecraft.\n', '', ''),
('cfm', 'MrCrayfish''s Furniture Mod', 'MrCrayfish''s Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates.', 'MrCrayfish', ''),
('codechickenlib', 'CodeChicken Lib', 'CodeChickenLib is a library of systems to help make various aspects of minecraft modding easier.\nIt contains libraries for 3D math and transformations, model rendering, packets, config, colours, asm and a few other things..\n', 'ChickenBones, covers1624', ''),
('controllable', 'Controllable', 'Adds the ability to use a controller to play Minecraft', '', 'https://mrcrayfish.com/modupdatejson?id=controllable'),
('croptopia', 'Croptopia', 'Crop mod for forge\r\n', 'Thonk, Rainbowcraft2', ''),
('curios', 'Curios API', 'A flexible and expandable accessory/equipment API for users and developers.\n', 'C4', ''),
('ftbbackups', 'FTB Backups', 'Creates backups of your world\n', 'LatvianModder', ''),
('ftbchunks', 'FTB Chunks', 'Claim chunks to protect your base from griefers!\n', 'LatvianModder', ''),
('ftbessentials', 'FTB Essentials', 'Adds many essential utility commands for servers\n', 'LatvianModder', ''),
('ftblibrary', 'FTB Library', 'FTB Library adds nothing.\n', 'LatvianModder', ''),
('ftbteams', 'FTB Teams', 'FTB Teams adds ability to create your own teams that can be used for quests etc.\n', 'LatvianModder', ''),
('goblintraders', 'Goblin Traders', 'Adds goblins that have unique trades to improve your adventure!', 'MrCrayfish', ''),
('immersiveengineering', 'Immersive Engineering', 'A tech based mod focused on realism.', 'BluSunrize and Damien A.W. Hazard', ''),
('indreb', 'Industrial Reborn', 'Industrial Reborn is a mod which adds many electrical machines, blocks, and items.', 'Maciej916', ''),
('infernalexp', 'Infernal Expansion', 'A community-driven Vanilla+ mod that expands the Nether beyond the Nether Update,\nintroducing new biomes, blocks, mobs, and more!\n\nDirector:\n- Nekomaster1000\n\nCoders:\n- BaconKami\n- Blackgear\n- CaelTheQuail\n- Dayton_10\n- Flenarn\n- HellionGames\n- LudoCrypt\n- Merxlc\n- Orcinus\n- SwanX1\n\nMain Artists:\n- Nekomaster1000\n- Sheddmer/Mocha\n- GLaDOS Edition\n- BaconKami\n\nMain Composers:\n- LudoCrypt\n\nSpecial Thanks:\n- JonahFuses\n- LiveVoxel\n- TelepathicGrunt\n', 'nekomaster1000', ''),
('ironchest', 'Iron Chests', 'New chests with larger sizes, with in-place upgrade items.\nThe feature chest is the crystal chest, which is transparent - some inventory contents are visible without opening the chest\n', 'cpw, alexbegt, progwml6', ''),
('ironshulkerbox', 'Iron Shulker Boxes', 'New Shulker Boxes with larger sizes, with in-place upgrade items.\nThe feature shulker box is the crystal chest, which is transparent - some inventory contents are visible without opening the shulker box \n', 'cpw, alexbegt, progwml6', ''),
('kotlinforforge', 'Kotlin for Forge', 'Kotlin for Forge. Allows mods to use the Kotlin programming language.\r\n', 'TheDarkColour', ''),
('mantle', 'Mantle', 'Shared code for Slime Knights mods and others.\n', 'Slime Knights', ''),
('morecfm', 'MrCrayfish''s More Furniture Mod', 'MrCrayfish''s More Furniture Mod is addon to the base Furniture Mod that adds support for wood variants from other mods', 'MrCrayfish', ''),
('obfuscate', 'Obfuscate', 'A simple library that adds in useful events', 'MrCrayfish', ''),
('optifine', 'OptiFine', 'OptiFine is a Minecraft optimization mod.\r\nIt allows Minecraft to run faster and look better with full support for shaders, HD textures and many configuration options.\r\n', 'sp614x', ''),
('pamhc2crops', 'Pam''s HarvestCraft 2 Crops', 'Pam''s HarvestCraft 2 Crops adds all new crops to the game\n', '', ''),
('pamhc2foodcore', 'Pam''s HarvestCraft 2 Food Core', 'Pam''s HarvestCraft 2 Food Core adds all new food to the game\n', '', ''),
('pamhc2foodextended', 'Pam''s HarvestCraft 2 Food Extended', 'Pam''s HarvestCraft 2 Food Extended adds all new food to the game\n', '', ''),
('pamhc2trees', 'Pam''s HarvestCraft 2 Fruit Trees', 'Pam''s HarvestCraft 2 Fruit Trees adds all new fruit trees to the game\n', '', ''),
('patchouli', 'Patchouli', 'Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers\n', 'Vazkii', ''),
('portabletanks', 'portabletanks', 'portabletanks adds portable tanks', 'Dremoline', ''),
('projecte', 'ProjectE', 'A complete rewrite of EE2 for modern Minecraft versions.', 'SinKillerJ, MaPePeR, williewillus, Lilylicious, pupnewfster', ''),
('projectred-core', 'ProjectRed Core', 'Redstone. The way it was meant to be.\n', 'MrTJP, Chicken Bones, covers1624', ''),
('projectred-exploration', 'ProjectRed Exploration', 'Redstone. The way it was meant to be.\n', 'MrTJP, Chicken Bones, covers1624', ''),
('projectred-illumination', 'ProjectRed Illumination', 'Redstone. The way it was meant to be.\n', 'MrTJP, Chicken Bones, covers1624', ''),
('projectred-integration', 'ProjectRed Integration', 'Redstone. The way it was meant to be.\n', 'MrTJP, Chicken Bones, covers1624', ''),
('recycler', 'Item Recycler', 'Adds a simple recycler block that lets you recycle items into their components\n', 'LatvianModder', ''),
('supermartijn642configlib', 'SuperMartijn642''s Config Lib', 'Config Lib makes dealing with config files just a bit easier.', 'SuperMartijn642', ''),
('supermartijn642corelib', 'SuperMartijn642''s Core Lib', 'SuperMartijn642''s Core Lib adds lots of basic implementations for guis that allow for similar code between Minecraft 1.12, 1.14, 1.15, and 1.16!', 'SuperMartijn642', ''),
('tconstruct', 'Tinkers'' Construct', 'A little of this, a little of that, a lot of tinkering, and a lot of tools\n', 'Slime Knights', ''),
('trashcans', 'Trash Cans', 'Trash Cans adds Trash Cans which can be used to void items, liquids and energy!', 'SuperMartijn642', ''),
('vehicle', 'MrCrayfish''s Vehicle Mod', 'A mod that adds vehicles into Minecraft!', 'MrCrayfish', '');
GO